# Generated by Django 2.1 on 2019-05-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
